@GateFlow.Api_HostAddress = http://127.0.0.1:8787

### Health
GET {{GateFlow.Api_HostAddress}}/health
Accept: application/json

###
GET {{GateFlow.Api_HostAddress}}/api/health
Accept: application/json

###
GET {{GateFlow.Api_HostAddress}}/swagger/index.html

###
