// <auto-generated />
using System;
using GateFlow.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GateFlow.Api.Migrations
{
    [DbContext(typeof(GateFlowDbContext))]
    partial class GateFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("GateFlow.Api.Models.AccessCredential", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitorPassId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.HasIndex("VisitorPassId")
                        .IsUnique();

                    b.HasIndex("SiteId", "Code");

                    b.HasIndex("SiteId", "Type", "Code")
                        .IsUnique();

                    b.ToTable("AccessCredentials");
                });

            modelBuilder.Entity("GateFlow.Api.Models.AccessEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LaneId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlateNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LaneId");

                    b.HasIndex("SiteId", "CreatedAt");

                    b.ToTable("AccessEvents");
                });

            modelBuilder.Entity("GateFlow.Api.Models.Lane", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceApiKey")
                        .IsUnique();

                    b.HasIndex("SiteId");

                    b.ToTable("Lanes");
                });

            modelBuilder.Entity("GateFlow.Api.Models.Site", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("GateFlow.Api.Models.Unit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Block")
                        .HasColumnType("TEXT");

                    b.Property<string>("Floor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Label")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("GateFlow.Api.Models.Vehicle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("SiteId", "PlateNumber")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("GateFlow.Api.Models.VisitorPass", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxUses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitId")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.HasIndex("UnitId");

                    b.ToTable("VisitorPasses");
                });

            modelBuilder.Entity("GateFlow.Api.Models.AccessCredential", b =>
                {
                    b.HasOne("GateFlow.Api.Models.Site", "Site")
                        .WithMany("Credentials")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GateFlow.Api.Models.Vehicle", "Vehicle")
                        .WithMany("Credentials")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GateFlow.Api.Models.VisitorPass", "VisitorPass")
                        .WithOne("Credential")
                        .HasForeignKey("GateFlow.Api.Models.AccessCredential", "VisitorPassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Site");

                    b.Navigation("Vehicle");

                    b.Navigation("VisitorPass");
                });

            modelBuilder.Entity("GateFlow.Api.Models.AccessEvent", b =>
                {
                    b.HasOne("GateFlow.Api.Models.Lane", "Lane")
                        .WithMany("Events")
                        .HasForeignKey("LaneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GateFlow.Api.Models.Site", "Site")
                        .WithMany("Events")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lane");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("GateFlow.Api.Models.Lane", b =>
                {
                    b.HasOne("GateFlow.Api.Models.Site", "Site")
                        .WithMany("Lanes")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("GateFlow.Api.Models.Unit", b =>
                {
                    b.HasOne("GateFlow.Api.Models.Site", "Site")
                        .WithMany("Units")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("GateFlow.Api.Models.Vehicle", b =>
                {
                    b.HasOne("GateFlow.Api.Models.Site", "Site")
                        .WithMany("Vehicles")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GateFlow.Api.Models.Unit", "Unit")
                        .WithMany("Vehicles")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Site");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("GateFlow.Api.Models.VisitorPass", b =>
                {
                    b.HasOne("GateFlow.Api.Models.Site", "Site")
                        .WithMany("VisitorPasses")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GateFlow.Api.Models.Unit", "Unit")
                        .WithMany("VisitorPasses")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Site");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("GateFlow.Api.Models.Lane", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("GateFlow.Api.Models.Site", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("Events");

                    b.Navigation("Lanes");

                    b.Navigation("Units");

                    b.Navigation("Vehicles");

                    b.Navigation("VisitorPasses");
                });

            modelBuilder.Entity("GateFlow.Api.Models.Unit", b =>
                {
                    b.Navigation("Vehicles");

                    b.Navigation("VisitorPasses");
                });

            modelBuilder.Entity("GateFlow.Api.Models.Vehicle", b =>
                {
                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("GateFlow.Api.Models.VisitorPass", b =>
                {
                    b.Navigation("Credential");
                });
#pragma warning restore 612, 618
        }
    }
}
